Using Mockaroo (https://mockaroo.com), generate 20 rows of data with the given structure. Save the data in the companies.csv file. Then, create a companies.ipynb notebook, in which create a DataFrame, based on the data contained in the CSV file. Display the contents of the DataFrame. Calculate and display:

* the total number of men working in companies
* average number of women working in companies

In [1]:
import pandas as pd

companies = pd.read_csv("companies.csv")
companies

       Company                Department  #Men  #Women
0      Blogtag                     Legal    81      49
1     Gigaclub                   Support    24      23
2        Jatri                  Services    12      88
3      Teklist        Product Management    78      65
4       Roodel        Product Management    24      79
5   Shuffletag                  Training    87      13
6    Browsebug           Human Resources    45      33
7       Trunyx  Research and Development    72      59
8     Bluezoom                  Services    52      21
9      Youopia                  Training    48      96
10       Eamia      Business Development    24      31
11       Vidoo                  Training    38      98
12       Tazzy               Engineering    73      91
13       Miboo                Accounting    56      98
14     Blogtag                  Training    72      63
15    Fivechat                  Services    55      80
16       Yabox                     Legal    46      33
17    Innotype                     Sales    48      84
18     Edgetag      Business Development    63      87
19    Livepath                  Services    29      89

In [2]:
companies["#Men"].sum()

1027

In [3]:
companies["#Women"].mean()

64.0